source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'csv'
gem 'jdbc-mariadb'
gem 'jdbc-mssql'
gem 'jdbc-mysql'
gem 'jdbc-postgresql'
gem 'jdbc-sqlite3'
gem 'jdbc'
gem 'json'
gem 'pry'
gem 'sequel'
gem 'slop'
gem 'warbler'